repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [ --maxkb=500 ]
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        exclude: mkdocs.yml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: pretty-format-json
        args: [ --autofix, --indent=4, --no-ensure-ascii, --no-sort-keys ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.19.0
    hooks:
      - id: markdownlint-cli2

  - repo: local
    hooks:
      - id: format
        name: Format
        entry: just
        args: [format]
        language: system
        types: [python]
        pass_filenames: false

      - id: lint
        name: Lint
        entry: just
        args: [lint]
        language: system
        types: [python]
        pass_filenames: false
