name: 🐛 Bug Report
description: Report a bug or unexpected behavior
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to Pydantic JSON Schema! 👺

  - type: checkboxes
    id: initial-checks
    attributes:
      label: Initial Checks
      options:
        - label: I confirm that I'm using the latest version of Pydantic JSON Schema
          required: true
        - label: I have searched the existing issues and this is a new bug
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain the bug and possible context.
        Please note that below you also have fields for minimal reproducible example, actual result and expected result.
        Provide as much context as possible to help us understand the issue.
    validations:
      required: true

  - type: textarea
    id: mre
    attributes:
      label: Minimal Reproducible Example
      description: |
        Please provide a minimal, reproducible example demonstrating the bug.
    validations:
      required: true

  - type: textarea
    id: mre_actual_result
    attributes:
      label: Actual Result
      description: |
        Please provide a result of the MRE above.
    validations:
      required: true

  - type: textarea
    id: mre_expected_result
    attributes:
      label: Expected Result
      description: |
        Please provide an expected result of the MRE above.
    validations:
      required: true

  - type: textarea
    id: versions
    attributes:
      label: Affected Versions Information
      description: |
        Please run the following command and copy the output below if applicable:

        ```bash
        uv run python -c "import sys, importlib.metadata as im; print(f'Python: {sys.version}\nPydantic: {im.version(\"pydantic\")}\nPydantic JSON Schema: {im.version(\"pydantic-jsonschema\")}')"
        ```
      placeholder: |
        Python: 3.14.0
        Pydantic: 2.13.0
        Pydantic JSON Schema: 1.0.0
    validations:
      required: false
